# Generated by Django 5.2.8 on 2026-05-04 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('direct_api', 'Direct API'), ('openrouter', 'OpenRouter'), ('deepseek', 'DeepSeek'), ('gemini_cli', 'Gemini CLI'), ('claude_code_cli', 'Claude Code CLI'), ('opencode', 'OpenCode')], max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('enabled', models.BooleanField(default=False)),
                ('worker_only', models.BooleanField(default=False)),
                ('api_key_env_var', models.CharField(blank=True, max_length=80)),
                ('default_tool_policy', models.CharField(choices=[('read_only', 'Read only'), ('workspace_write', 'Workspace write'), ('safe_shell', 'Safe shell'), ('network_tools', 'Network tools'), ('external_action', 'External action')], default='read_only', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('profile_builder', 'Profile Builder'), ('match_review', 'Match Review'), ('search_strategy', 'Search Strategy')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('provider', models.CharField(choices=[('direct_api', 'Direct API'), ('openrouter', 'OpenRouter'), ('deepseek', 'DeepSeek'), ('gemini_cli', 'Gemini CLI'), ('claude_code_cli', 'Claude Code CLI'), ('opencode', 'OpenCode')], default='direct_api', max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('tool_policy', models.CharField(choices=[('read_only', 'Read only'), ('workspace_write', 'Workspace write'), ('safe_shell', 'Safe shell'), ('network_tools', 'Network tools'), ('external_action', 'External action')], default='read_only', max_length=40)),
                ('prompt_version', models.CharField(default='local-profile-builder-v1', max_length=80)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('user_safe_error', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-requested_at', '-created_at'],
                'indexes': [models.Index(fields=['agent_type', 'status'], name='agents_agen_agent_t_53b5de_idx'), models.Index(fields=['provider', 'status'], name='agents_agen_provide_4dc409_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_level', models.CharField(choices=[('read_only', 'Read only'), ('workspace_write', 'Workspace write'), ('safe_shell', 'Safe shell'), ('network_tools', 'Network tools'), ('external_action', 'External action')], max_length=40)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('blocked', 'Blocked')], default='granted', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='agents.agentrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('question', models.TextField()),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agents.agentrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='agents.agentrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('markdown', 'Markdown'), ('json', 'JSON'), ('text', 'Text'), ('proposal', 'Proposal')], default='markdown', max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='agents.agentrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting_approval', 'Waiting approval'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.agentrun')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('adapter', models.CharField(max_length=80)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='prepared', max_length=20)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_snapshot', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('cost_estimate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_invocations', to='agents.agentrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
