# Generated by Django 5.2.8 on 2026-05-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprovidersetting',
            name='consent_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprovidersetting',
            name='daily_run_limit',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='agentprovidersetting',
            name='estimated_cost_per_run_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentprovidersetting',
            name='monthly_budget_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
