# Generated by Django 5.2.8 on 2026-05-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentprovidersetting_consent_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(choices=[('profile_builder', 'Profile Builder'), ('match_review', 'Match Review'), ('search_strategy', 'Search Strategy'), ('application_prep', 'Application Prep'), ('follow_up', 'Follow-Up')], max_length=40),
        ),
    ]
