# Generated by Django 5.2.8 on 2026-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentrun_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='agent_type',
            field=models.CharField(choices=[('profile_builder', 'Profile Builder'), ('source_discovery', 'Source Discovery'), ('match_review', 'Match Review'), ('search_strategy', 'Search Strategy'), ('notification_review', 'Notification Review')], max_length=40),
        ),
    ]
