# Generated by Django 5.2.8 on 2026-05-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentrun_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprovidersetting',
            name='provider',
            field=models.CharField(choices=[('direct_api', 'Direct API'), ('openrouter', 'OpenRouter'), ('deepseek', 'DeepSeek'), ('gemini_cli', 'Gemini CLI'), ('claude_code_cli', 'Claude Code CLI'), ('codex_cli', 'Codex CLI'), ('opencode', 'OpenCode')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='provider',
            field=models.CharField(choices=[('direct_api', 'Direct API'), ('openrouter', 'OpenRouter'), ('deepseek', 'DeepSeek'), ('gemini_cli', 'Gemini CLI'), ('claude_code_cli', 'Claude Code CLI'), ('codex_cli', 'Codex CLI'), ('opencode', 'OpenCode')], default='direct_api', max_length=40),
        ),
    ]
