from django.urls import path

from . import views


urlpatterns = [
    path("health", views.health, name="api_health"),
    path("diagnostics", views.diagnostics, name="api_diagnostics"),
    path("profile", views.profile_detail, name="api_profile"),
    path("profile/import-resume", views.profile_import_resume, name="api_profile_import_resume"),
    path("profile/generate-titles", views.profile_generate_titles, name="api_profile_generate_titles"),
    path("profile/apply-titles-to-companies", views.profile_apply_titles_to_companies, name="api_profile_apply_titles"),
    path("profile/search-strategy", views.profile_search_strategy_detail, name="api_profile_search_strategy"),
    path("profile/search-strategy/generate", views.profile_generate_search_strategy, name="api_profile_generate_search_strategy"),
    path("profile/search-strategy/apply-to-companies", views.profile_apply_search_strategy, name="api_profile_apply_search_strategy"),
    path("profile/target-titles/<int:title_id>/<str:status>", views.target_title_status, name="api_target_title_status"),
    path("profile/claims/<int:claim_id>/<str:status>", views.profile_claim_status, name="api_profile_claim_status"),
    path("notifications/preferences", views.notification_preferences_detail, name="api_notification_preferences"),
    path("companies", views.companies_list, name="api_companies"),
    path("companies/import-csv", views.companies_import_csv, name="api_companies_import_csv"),
    path("companies/logs", views.company_logs_all, name="api_company_logs_all"),
    path("companies/<int:company_id>", views.company_detail, name="api_company_detail"),
    path("companies/<int:company_id>/pause", views.company_pause, name="api_company_pause"),
    path("companies/<int:company_id>/resume", views.company_resume, name="api_company_resume"),
    path("companies/<int:company_id>/discover-source", views.company_discover_source, name="api_company_discover_source"),
    path("companies/<int:company_id>/sources", views.company_sources_list, name="api_company_sources"),
    path("companies/<int:company_id>/sources/<int:source_id>", views.company_source_detail, name="api_company_source_detail"),
    path("companies/<int:company_id>/crawl", views.company_crawl, name="api_company_crawl"),
    path("companies/<int:company_id>/rescan", views.company_crawl, name="api_company_rescan"),
    path("crawls", views.crawl_runs_list, name="api_crawl_runs"),
    path("crawls/run-due", views.crawl_run_due, name="api_crawl_run_due"),
    path("scans", views.crawl_runs_list, name="api_scan_jobs"),
    path("scans/run", views.crawl_run_due, name="api_scan_run"),
    path("jobs", views.jobs_list, name="api_jobs"),
    path("jobs/<int:job_id>", views.job_detail, name="api_job_detail"),
    path("jobs/<int:job_id>/feedback", views.job_feedback, name="api_job_feedback"),
    path("agents/providers", views.agent_providers_list, name="api_agent_providers"),
    path("agents/providers/<str:provider>", views.agent_provider_detail, name="api_agent_provider_detail"),
    path("agents/runtime", views.agent_runtime_detail, name="api_agent_runtime"),
    path("agents/runs", views.agent_runs_list, name="api_agent_runs"),
    path("agents/runs/<int:run_id>", views.agent_run_detail, name="api_agent_run_detail"),
    path("agents/runs/<int:run_id>/cancel", views.agent_run_cancel, name="api_agent_run_cancel"),
    path("agents/runs/<int:run_id>/retry", views.agent_run_retry, name="api_agent_run_retry"),
    path("agents/decisions/<int:decision_id>/<str:status>", views.agent_decision_status, name="api_agent_decision_status"),
]
