# Generated by Django 5.2.8 on 2026-05-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_status'),
        ('matching', '0002_matchfeedback_jobmatch_agent_review_status_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='immediate_email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='max_digest_items',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='minimum_confidence_score',
            field=models.PositiveIntegerField(default=55),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='minimum_match_score',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='digest_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('disabled', 'Disabled')], default='daily', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('local', 'Local'), ('email', 'Email')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('score_at_send', models.PositiveIntegerField(default=0)),
                ('confidence_at_send', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('skipped_reason', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='jobs.job')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_events', to='matching.jobmatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_b39d22_idx'), models.Index(fields=['job', 'channel'], name='notificatio_job_id_71c99f_idx')],
            },
        ),
    ]
