services:
  - type: web
    name: company-job-scraper
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn jobhunt.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        sync: false
