TOP_TIER_COMPANIES = [
    # ── Big Tech ──────────────────────────────────────────────────────────────
    ("Microsoft",       "https://apply.careers.microsoft.com/careers?start=0&sort_by=relevance&filter_include_remote=1", "generic"),
    ("Google",          "https://www.google.com/about/careers/applications/jobs/results", "generic"),
    ("Amazon",          "https://www.amazon.jobs/en/search", "generic"),
    ("Apple",           "https://jobs.apple.com/en-us/search", "generic"),
    ("Meta",            "https://www.metacareers.com/jobs", "generic"),
    ("NVIDIA",          "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite", "generic"),
    ("Netflix",         "https://explore.jobs.netflix.net/careers", "generic"),
    ("Adobe",           "https://careers.adobe.com/us/en/search-results", "generic"),
    ("Salesforce",      "https://salesforce.wd1.myworkdayjobs.com/External_Career_Site", "generic"),
    ("LinkedIn",        "https://careers.linkedin.com/jobs", "generic"),
    ("Intel",           "https://jobs.intel.com/en/search-jobs", "generic"),
    ("IBM",             "https://www.ibm.com/careers/search", "generic"),
    ("Oracle",          "https://careers.oracle.com/jobs/#en/sites/jobsearch/jobs", "generic"),
    ("Qualcomm",        "https://careers.qualcomm.com/careers/search", "generic"),
    ("Twitter / X",     "https://careers.x.com/en", "generic"),
    ("SAP",             "https://jobs.sap.com/search/", "generic"),
    ("Cisco",           "https://jobs.cisco.com/jobs/SearchJobs", "generic"),

    # ── AI / ML ───────────────────────────────────────────────────────────────
    ("OpenAI",          "https://jobs.ashbyhq.com/OpenAI", "ashby"),
    ("Anthropic",       "https://job-boards.greenhouse.io/anthropic", "greenhouse"),
    ("Cohere",          "https://job-boards.greenhouse.io/cohere", "greenhouse"),
    ("Perplexity",      "https://job-boards.greenhouse.io/perplexityai", "greenhouse"),
    ("Mistral AI",      "https://jobs.lever.co/mistralai", "lever"),
    ("Scale AI",        "https://scale.com/careers", "generic"),
    ("Hugging Face",    "https://apply.workable.com/huggingface/", "generic"),
    ("Together AI",     "https://job-boards.greenhouse.io/togethercomputer", "greenhouse"),
    ("Cursor",          "https://jobs.ashbyhq.com/anysphere", "ashby"),
    ("Replicate",       "https://jobs.ashbyhq.com/replicate", "ashby"),
    ("ElevenLabs",      "https://jobs.ashbyhq.com/elevenlabs", "ashby"),
    ("Groq",            "https://job-boards.greenhouse.io/groq", "greenhouse"),
    ("xAI",             "https://job-boards.greenhouse.io/xai", "greenhouse"),
    ("Sarvam AI",       "https://jobs.lever.co/sarvamai", "lever"),
    ("Krutrim",         "https://krutrim.com/careers", "generic"),

    # ── High-growth Tech ──────────────────────────────────────────────────────
    ("Stripe",          "https://stripe.com/jobs/search", "generic"),
    ("Shopify",         "https://www.shopify.com/careers", "generic"),
    ("Cloudflare",      "https://www.cloudflare.com/careers/jobs/", "generic"),
    ("GitHub",          "https://www.github.careers/careers-home/jobs", "generic"),
    ("Databricks",      "https://www.databricks.com/company/careers/open-positions", "generic"),
    ("Notion",          "https://www.notion.com/careers", "generic"),
    ("Figma",           "https://job-boards.greenhouse.io/figma", "greenhouse"),
    ("Canva",           "https://www.canva.com/careers/", "generic"),
    ("Atlassian",       "https://www.atlassian.com/company/careers/all-jobs", "generic"),
    ("Snowflake",       "https://careers.snowflake.com/jobs", "generic"),
    ("HashiCorp",       "https://www.hashicorp.com/careers", "generic"),
    ("Vercel",          "https://vercel.com/careers", "generic"),
    ("Supabase",        "https://supabase.com/careers", "generic"),
    ("Linear",          "https://linear.app/careers", "generic"),
    ("Twilio",          "https://job-boards.greenhouse.io/twilio", "greenhouse"),
    ("Reddit",          "https://job-boards.greenhouse.io/reddit", "greenhouse"),
    ("Lyft",            "https://job-boards.greenhouse.io/lyft", "greenhouse"),
    ("Uber",            "https://www.uber.com/us/en/careers/list/", "generic"),
    ("Airbnb",          "https://careers.airbnb.com/positions/", "generic"),
    ("DoorDash",        "https://careers.doordash.com/jobs", "generic"),
    ("Coinbase",        "https://www.coinbase.com/careers/positions", "generic"),
    ("Palantir",        "https://jobs.lever.co/palantir", "lever"),
    ("Spotify",         "https://jobs.lever.co/spotify", "lever"),
    ("Zoom",            "https://jobs.lever.co/zoom", "lever"),
    ("Block",           "https://jobs.lever.co/block", "lever"),
    ("HubSpot",         "https://www.hubspot.com/careers/jobs", "generic"),
    ("Dropbox",         "https://jobs.dropbox.com/all-jobs", "generic"),
    ("Pinterest",       "https://www.pinterestcareers.com/jobs/", "generic"),
    ("Airtable",        "https://job-boards.greenhouse.io/airtable", "greenhouse"),
    ("Webflow",         "https://job-boards.greenhouse.io/webflow", "greenhouse"),
    ("Retool",          "https://job-boards.greenhouse.io/retool", "greenhouse"),
    ("Loom",            "https://job-boards.greenhouse.io/loom", "greenhouse"),
    ("Miro",            "https://miro.com/careers/", "generic"),
    ("Brex",            "https://www.brex.com/careers", "generic"),
    ("Rippling",        "https://www.rippling.com/careers", "generic"),
    ("Gusto",           "https://gusto.com/about/careers", "generic"),
    ("Deel",            "https://www.deel.com/careers", "generic"),
    ("PostHog",         "https://posthog.com/careers", "generic"),
    ("Sentry",          "https://sentry.io/careers/", "generic"),
    ("Grafana Labs",    "https://grafana.com/about/careers/", "generic"),
    ("GitLab",          "https://about.gitlab.com/jobs/", "generic"),
    ("Wix",             "https://www.wix.com/jobs/locations/tel-aviv", "generic"),

    # ── Indian Unicorns & Startups ────────────────────────────────────────────
    ("Flipkart",        "https://www.flipkartcareers.com/#!/joblist", "generic"),
    ("Swiggy",          "https://careers.swiggy.com/", "generic"),
    ("Zomato",          "https://www.zomato.com/careers", "generic"),
    ("Razorpay",        "https://razorpay.com/jobs/", "generic"),
    ("CRED",            "https://careers.cred.club/", "generic"),
    ("PhonePe",         "https://www.phonepe.com/careers/", "generic"),
    ("Meesho",          "https://meesho.io/jobs", "generic"),
    ("Zepto",           "https://www.zeptonow.com/careers", "generic"),
    ("Groww",           "https://groww.in/careers", "generic"),
    ("Zerodha",         "https://zerodha.com/careers/", "generic"),
    ("Freshworks",      "https://careers.freshworks.com/jobs", "generic"),
    ("Ola",             "https://ola.cars/careers", "generic"),
    ("Nykaa",           "https://jobs.nykaa.com/", "generic"),
    ("Dream11",         "https://dream11.hire.trakstar.com/", "generic"),
    ("MPL",             "https://www.mpl.live/careers", "generic"),
    ("Paytm",           "https://careers.paytm.com/", "generic"),
    ("MakeMyTrip",      "https://careers.makemytrip.com/", "generic"),
    ("PolicyBazaar",    "https://www.policybazaar.com/careers/", "generic"),
    ("Urban Company",   "https://careers.urbancompany.com/", "generic"),
    ("Lenskart",        "https://www.lenskart.com/careers.html", "generic"),
    ("Cars24",          "https://www.cars24.com/careers/", "generic"),
    ("Delhivery",       "https://www.delhivery.com/careers", "generic"),
    ("Shiprocket",      "https://careers.shiprocket.in/", "generic"),
    ("Porter",          "https://porter.in/careers", "generic"),
    ("Dunzo",           "https://www.dunzo.com/blog/careers", "generic"),
    ("ShareChat",       "https://sharechat.com/careers", "generic"),
    ("Rapido",          "https://rapido.bike/careers/", "generic"),
    ("Slice",           "https://www.sliceit.com/careers", "generic"),
    ("Fi Money",        "https://fi.money/careers", "generic"),
    ("Jupiter",         "https://jupiter.money/careers/", "generic"),
    ("Jar",             "https://www.myjar.app/careers", "generic"),
    ("Cashfree",        "https://www.cashfree.com/company/careers/", "generic"),
    ("Juspay",          "https://juspay.in/careers", "generic"),
    ("BrowserStack",    "https://www.browserstack.com/careers", "generic"),
    ("Postman",         "https://www.postman.com/company/careers/", "generic"),
    ("Hasura",          "https://hasura.io/careers/", "generic"),
    ("Chargebee",       "https://www.chargebee.com/careers/", "generic"),
    ("Zoho",            "https://careers.zohocorp.com/jobs/Careers", "generic"),
    ("CleverTap",       "https://clevertap.com/careers/", "generic"),
    ("MoEngage",        "https://www.moengage.com/careers/", "generic"),
    ("Darwinbox",       "https://darwinbox.com/careers", "generic"),
    ("LeadSquared",     "https://www.leadsquared.com/careers/", "generic"),
    ("Innovaccer",      "https://innovaccer.com/company/careers/", "generic"),
    ("Zetwerk",         "https://www.zetwerk.com/careers/", "generic"),
    ("Moglix",          "https://www.moglix.com/careers", "generic"),
    ("Udaan",           "https://udaan.com/careers.html", "generic"),
    ("Ninjacart",       "https://ninjacart.com/careers/", "generic"),
    ("Healthifyme",     "https://www.healthifyme.com/blog/careers/", "generic"),
    ("Cult.fit",        "https://cult.fit/cult-careers", "generic"),
    ("1mg",             "https://www.1mg.com/careers", "generic"),
    ("Practo",          "https://practo.com/company/careers", "generic"),
    ("PharmEasy",       "https://pharmeasy.in/blog/careers/", "generic"),
    ("Infosys",         "https://career.infosys.com/joblist", "generic"),
    ("Wipro",           "https://careers.wipro.com/careers-home/", "generic"),
    ("HCL Tech",        "https://www.hcltech.com/careers", "generic"),
    ("Tech Mahindra",   "https://careers.techmahindra.com/", "generic"),
]
