# Generated by Django 5.2.8 on 2026-05-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_alert_new_roles_company_scan_frequency_hours_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('relevant', 'Relevant'), ('maybe', 'Maybe'), ('irrelevant', 'Irrelevant')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='companies.jobalert')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_feedback', to='companies.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_feedback', to='jobs.job')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['rating', 'updated_at'], name='analytics_a_rating_963004_idx'), models.Index(fields=['company', 'rating'], name='analytics_a_company_2de990_idx')],
            },
        ),
    ]
