# Generated by Django 5.2.8 on 2026-05-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_weeklyreview'),
        ('jobs', '0001_initial'),
        ('profiles', '0003_searchstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('undone', 'Undone')], default='active', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['change_type', 'status'], name='analytics_l_change__974933_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchScoreCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.CharField(choices=[('too_high', 'Score too high'), ('accurate', 'Accurate'), ('too_low', 'Score too low')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_corrections', to='jobs.job')),
                ('learning_change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_score_correction', to='analytics.learningchange')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_score_corrections', to='profiles.candidateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='analytics_m_job_id_6d057c_idx'), models.Index(fields=['correction', 'created_at'], name='analytics_m_correct_b0c8a5_idx')],
            },
        ),
    ]
