# Generated by Django 5.2.8 on 2026-05-04 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_alert_new_roles_company_scan_frequency_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=180)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('contacted', 'Contacted'), ('responded', 'Responded'), ('not_relevant', 'Not relevant')], default='lead', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_contacts', to='companies.company')),
            ],
            options={
                'ordering': ['company', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('hiring_signals', models.JSONField(blank=True, default=list)),
                ('role_patterns', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.CharField(default='deterministic', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_reports', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='intelligenc_company_b0bb61_idx')],
            },
        ),
    ]
