# Generated by Django 5.2.8 on 2026-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyintelligence',
            name='caveats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyintelligence',
            name='hiring_team_hints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='companyintelligence',
            name='interview_process_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyintelligence',
            name='research_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyintelligence',
            name='role_legitimacy',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('likely_legitimate', 'Likely legitimate'), ('needs_review', 'Needs review'), ('high_risk', 'High risk')], default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='companyintelligence',
            name='user_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyintelligence',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('deterministic', 'Deterministic'), ('user_verified', 'User verified')], default='unverified', max_length=40),
        ),
        migrations.AddField(
            model_name='recruitercontact',
            name='public_source_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recruitercontact',
            name='source_label',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
