# Generated by Django 5.2.8 on 2026-05-04 20:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('deterministic', 'Deterministic'), ('agent', 'Agent')], default='deterministic', max_length=40)),
                ('profile_updated_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.PositiveIntegerField(default=0)),
                ('title_score', models.PositiveIntegerField(default=0)),
                ('skill_score', models.PositiveIntegerField(default=0)),
                ('seniority_score', models.PositiveIntegerField(default=0)),
                ('location_score', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.PositiveIntegerField(default=0)),
                ('knowledge_coverage_score', models.PositiveIntegerField(default=0)),
                ('apply_priority', models.CharField(choices=[('apply_now', 'Apply now'), ('consider', 'Consider'), ('stretch', 'Stretch'), ('ignore', 'Ignore')], default='ignore', max_length=20)),
                ('reasons_to_apply', models.JSONField(blank=True, default=list)),
                ('reasons_to_skip', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_report', to='jobs.job')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_matches', to='profiles.candidateprofile')),
            ],
            options={
                'ordering': ['-overall_score', '-confidence_score', '-generated_at'],
                'indexes': [models.Index(fields=['apply_priority', '-overall_score'], name='matching_jo_apply_p_bb0795_idx'), models.Index(fields=['overall_score', 'confidence_score'], name='matching_jo_overall_641a33_idx')],
            },
        ),
    ]
