# Generated by Django 5.2.8 on 2026-05-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_status'),
        ('matching', '0001_initial'),
        ('profiles', '0004_usersearchpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('good_match', 'Good match'), ('bad_match', 'Bad match'), ('too_senior', 'Too senior'), ('too_junior', 'Too junior'), ('wrong_location', 'Wrong location'), ('wrong_role', 'Wrong role'), ('missing_skill', 'Missing skill'), ('not_interested_company', 'Not interested company'), ('too_many_notifications', 'Too many notifications'), ('want_more_matches', 'Want more matches')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='agent_review_status',
            field=models.CharField(default='not_requested', max_length=40),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='agent_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='feature_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='model_version',
            field=models.CharField(default='weighted-v1', max_length=80),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='notification_threshold',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='should_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='source',
            field=models.CharField(choices=[('deterministic', 'Deterministic'), ('weighted', 'Weighted feature scorer'), ('agent', 'Agent')], default='deterministic', max_length=40),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['should_notify', '-overall_score'], name='matching_jo_should__baee01_idx'),
        ),
        migrations.AddField(
            model_name='matchfeedback',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_feedback', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='matchfeedback',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='matching.jobmatch'),
        ),
        migrations.AddField(
            model_name='matchfeedback',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_feedback', to='profiles.candidateprofile'),
        ),
        migrations.AddIndex(
            model_name='matchfeedback',
            index=models.Index(fields=['feedback_type', 'created_at'], name='matching_ma_feedbac_2263dd_idx'),
        ),
        migrations.AddIndex(
            model_name='matchfeedback',
            index=models.Index(fields=['job', 'feedback_type'], name='matching_ma_job_id_fb3b8f_idx'),
        ),
    ]
