# Generated by Django 5.2.8 on 2026-05-04 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_applicationartifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('question_bank', models.JSONField(blank=True, default=list)),
                ('story_bank', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.CharField(default='deterministic', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_prep', to='applications.application')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_criteria', models.JSONField(blank=True, default=list)),
                ('negotiation_points', models.JSONField(blank=True, default=list)),
                ('compensation_notes', models.TextField(blank=True)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('generated_by', models.CharField(default='deterministic', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_support', to='applications.application')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
