# Generated by Django 5.2.8 on 2026-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewprep',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewprep',
            name='stage',
            field=models.CharField(choices=[('screen', 'Screen'), ('technical', 'Technical'), ('onsite', 'Onsite'), ('final', 'Final'), ('unknown', 'Unknown')], default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='offersupport',
            name='base_salary_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offersupport',
            name='base_salary_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offersupport',
            name='benefits_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offersupport',
            name='equity_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offersupport',
            name='manual_research',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='offersupport',
            name='offer_stage',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
