# Generated by Django 5.2.8 on 2026-05-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_alert_new_roles_company_scan_frequency_hours_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applying', 'Applying'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('skipped', 'Skipped')], default='saved', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='jobs.job')),
                ('source_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='companies.jobalert')),
            ],
            options={
                'ordering': ['follow_up_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TodayAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('review_new_role', 'Review new role'), ('follow_up', 'Follow up'), ('application_next_step', 'Application next step')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_actions', to='applications.application')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_actions', to='jobs.job')),
                ('source_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_actions', to='companies.jobalert')),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'follow_up_at'], name='application_status_242cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['updated_at'], name='application_updated_af10bf_idx'),
        ),
        migrations.AddIndex(
            model_name='todayaction',
            index=models.Index(fields=['status', 'due_at'], name='application_status_043a69_idx'),
        ),
        migrations.AddIndex(
            model_name='todayaction',
            index=models.Index(fields=['action_type', 'status'], name='application_action__6ccc3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='todayaction',
            constraint=models.UniqueConstraint(fields=('source_alert', 'action_type'), name='unique_today_action_per_alert_type'),
        ),
        migrations.AddConstraint(
            model_name='todayaction',
            constraint=models.UniqueConstraint(fields=('application', 'action_type'), name='unique_today_action_per_application_type'),
        ),
    ]
