# Generated by Django 5.2.8 on 2026-05-04 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('tailoring_plan', 'Tailoring plan'), ('cv_notes', 'CV notes'), ('cover_note', 'Cover note'), ('recruiter_message', 'Recruiter message'), ('answer_bank', 'Answer bank'), ('interview_seed', 'Interview seed')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.CharField(default='deterministic', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='applications.application')),
            ],
            options={
                'ordering': ['application', 'artifact_type', '-created_at'],
                'indexes': [models.Index(fields=['application', 'artifact_type', 'status'], name='application_applica_2b26ed_idx')],
            },
        ),
    ]
