# Generated by Django 5.2.8 on 2026-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('notified', 'Notified'), ('saved', 'Saved'), ('dismissed', 'Dismissed'), ('stale', 'Stale'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
