# Generated by Django 5.2.8 on 2026-05-04 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_alert_new_roles_company_scan_frequency_hours_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUrlInboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('item_type', models.CharField(choices=[('unknown', 'Unknown'), ('company', 'Company'), ('job', 'Job')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('inferred_company', models.CharField(blank=True, max_length=180)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_inbox_items', to='companies.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_inbox_items', to='jobs.job')),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', 'item_type', 'created_at'], name='discovery_m_status_6e4247_idx')],
            },
        ),
    ]
