# Generated by Django 5.2.8 on 2026-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_seed_top_tier_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='consecutive_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='last_failed_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_new_role_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_successful_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='priority_tier',
            field=models.CharField(choices=[('dream', 'Dream'), ('high', 'High'), ('normal', 'Normal'), ('fallback', 'Fallback')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='source_health',
            field=models.CharField(choices=[('needs_setup', 'Needs setup'), ('active', 'Active'), ('degraded', 'Degraded'), ('failing', 'Failing'), ('paused', 'Paused'), ('blocked', 'Blocked')], default='needs_setup', max_length=20),
        ),
    ]
