# Generated by Django 5.2.8 on 2026-05-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_consecutive_failure_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='negative_title_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='title_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='work_mode_filter',
            field=models.CharField(choices=[('any', 'Any'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='any', max_length=20),
        ),
    ]
