# Generated by Django 5.2.8 on 2026-05-04 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_location_keywords_and_more'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='alert_new_roles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='scan_frequency_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('command', 'Command')], default='manual', max_length=20)),
                ('source_platform', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('jobs_found', models.PositiveIntegerField(default=0)),
                ('jobs_created', models.PositiveIntegerField(default=0)),
                ('jobs_updated', models.PositiveIntegerField(default=0)),
                ('alerts_created', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='companies.company')),
                ('scrape_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_job', to='companies.scrapelog')),
            ],
            options={
                'ordering': ['-requested_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('new_role', 'New role')], default='new_role', max_length=40)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='companies.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='jobs.job')),
                ('scan_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='companies.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['company', 'status'], name='companies_s_company_6d5593_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status', 'requested_at'], name='companies_s_status_a1747b_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['status', 'created_at'], name='companies_j_status_af55de_idx'),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(fields=['company', 'status'], name='companies_j_company_392b59_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobalert',
            constraint=models.UniqueConstraint(fields=('company', 'job', 'alert_type'), name='unique_job_alert_per_company_job_type'),
        ),
    ]
