# Generated by Django 5.2.8 on 2026-05-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_alert_new_roles_company_scan_frequency_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyJobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source_type', models.CharField(choices=[('careers', 'Careers'), ('jobs', 'Jobs'), ('ats', 'ATS'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='careers', max_length=20)),
                ('platform', models.CharField(default='unknown', max_length=40)),
                ('discovery_method', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('deterministic_agent', 'Deterministic agent'), ('llm_agent', 'LLM agent')], default='deterministic_agent', max_length=40)),
                ('confidence_score', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_review', 'Needs review'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='needs_review', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company__name', '-is_primary', '-confidence_score', 'url'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='company',
            name='homepage_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='source_discovery_confidence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='source_discovery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='source_discovery_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('queued', 'Queued'), ('found', 'Found'), ('needs_review', 'Needs review'), ('failed', 'Failed'), ('manual', 'Manual')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='careers_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='source_health',
            field=models.CharField(choices=[('needs_setup', 'Needs setup'), ('needs_source', 'Needs source'), ('needs_review', 'Needs review'), ('active', 'Active'), ('degraded', 'Degraded'), ('failing', 'Failing'), ('paused', 'Paused'), ('blocked', 'Blocked')], default='needs_setup', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('domain', ''), _negated=True), fields=('domain',), name='unique_company_domain_when_present'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('careers_url', ''), _negated=True), fields=('careers_url',), name='unique_company_careers_url_when_present'),
        ),
        migrations.AddField(
            model_name='companyjobsource',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sources', to='companies.company'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_runs', to='companies.companyjobsource'),
        ),
        migrations.AddField(
            model_name='scrapelog',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_logs', to='companies.companyjobsource'),
        ),
        migrations.AddIndex(
            model_name='companyjobsource',
            index=models.Index(fields=['company', 'status'], name='companies_c_company_b35ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='companyjobsource',
            index=models.Index(fields=['is_primary', 'status'], name='companies_c_is_prim_ab25e3_idx'),
        ),
    ]
