# Generated by Django 5.2.8 on 2026-05-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('remote_preference', models.CharField(choices=[('any', 'Any'), ('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='any', max_length=20)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('preferred_work_modes', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('dealbreakers', models.TextField(blank=True)),
                ('compensation_expectation', models.CharField(blank=True, max_length=180)),
                ('cv_markdown', models.TextField(blank=True)),
                ('profile_markdown', models.TextField(blank=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'candidate profile',
                'verbose_name_plural': 'candidate profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('skill', 'Skill'), ('experience', 'Experience'), ('project', 'Project'), ('metric', 'Metric'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=40)),
                ('text', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('source', models.CharField(default='resume_import', max_length=40)),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('needs_edit', 'Needs edit'), ('rejected', 'Rejected')], default='unconfirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='profiles.candidateprofile')),
            ],
            options={
                'ordering': ['status', 'claim_type', 'id'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'text'), name='unique_profile_claim_text')],
            },
        ),
        migrations.CreateModel(
            name='TargetTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('fit_bucket', models.CharField(choices=[('core', 'Core'), ('adjacent', 'Adjacent'), ('stretch', 'Stretch')], default='adjacent', max_length=20)),
                ('confidence_score', models.PositiveIntegerField(default=50)),
                ('knowledge_accuracy', models.PositiveIntegerField(default=50)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='deterministic', max_length=40)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_titles', to='profiles.candidateprofile')),
            ],
            options={
                'ordering': ['status', '-confidence_score', 'title'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'title'), name='unique_target_title_per_profile')],
            },
        ),
    ]
