# Generated by Django 5.2.8 on 2026-05-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='career_timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_completeness_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_yml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='proof_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='role_framing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skill_inventory',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
