# Generated by Django 5.2.8 on 2026-05-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_candidateprofile_career_timeline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_families', models.JSONField(blank=True, default=list)),
                ('target_title_keywords', models.JSONField(blank=True, default=list)),
                ('negative_keywords', models.JSONField(blank=True, default=list)),
                ('seniority_levels', models.JSONField(blank=True, default=list)),
                ('location_keywords', models.JSONField(blank=True, default=list)),
                ('work_mode_preferences', models.JSONField(blank=True, default=list)),
                ('generated_from', models.CharField(default='deterministic_profile', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_strategy', to='profiles.candidateprofile')),
            ],
            options={
                'verbose_name': 'search strategy',
                'verbose_name_plural': 'search strategies',
            },
        ),
    ]
