# Generated by Django 5.2.8 on 2026-05-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_searchstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_match_score', models.PositiveIntegerField(default=70)),
                ('minimum_confidence_score', models.PositiveIntegerField(default=55)),
                ('match_strictness', models.CharField(choices=[('loose', 'Loose'), ('balanced', 'Balanced'), ('strict', 'Strict')], default='balanced', max_length=20)),
                ('preferred_seniority', models.JSONField(blank=True, default=list)),
                ('excluded_keywords', models.JSONField(blank=True, default=list)),
                ('excluded_companies', models.JSONField(blank=True, default=list)),
                ('feedback_weights', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preferences', to='profiles.candidateprofile')),
            ],
            options={
                'verbose_name': 'user search preference',
                'verbose_name_plural': 'user search preferences',
            },
        ),
    ]
